swipe:
  3: 
    left: 
      command: 'xdotool key super+Right'
    right: 
      command: 'xdotool key super+Left'
    up: 
      command: 'xdotool key super+Down'
    down: 
      command: 'xdotool key super+Up'
  4:
    left: 
      command: 'xdotool key super+alt+Left'
    right: 
      command: 'xdotool key super+alt+Right'
    up: 
      command: 'xdotool key super+a'
    down: 
      command: 'xdotool key super+s'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 1
  pinch: 1
